---
weblog_db: YOUR_DATABASE
weblog_tb: YOUR_TABLE
if_flag: true #true or false
for_each_02:
- first: aaa
  second: bbb
- first: ccc
  second: ddd
to_gs:
- connecter: YOUR_GOOGLE_SHEETS_CONNECTER_NAME
  folder: YOUR_GOOGLE_DRIVE_FOLDER_KEY
master_segment: 111111