---
firsttime_flag: true #true or false / read_depth cnt exists true
check_js_extension: -- #extensionを使用している場合は空白
session_term: 1800 #秒数→セッショナイズする間隔設定
media:
- media_name: sanple_1
  log_db: YOUR_WEB_LOG_DB #set web_log database
  log_tb: YOUR_WEB_LOG_TB #set web_log table
  primary_cookie: td_client_id #or td_ssc_id
  check_td_ssc_id:  -- #td_ssc_idをONにする場合は空白
  check_user_id:  #user_idをONにする場合は空白
  user_id: user_id #set user_id column
