---
firsttime_flag: true #true or false / read_depth cnt exists true
check_js_extension: -- #extensionを使用している場合は空白
session_term: 1800 #秒数→セッショナイズする間隔設定
media:
- media_name: sample_1
  log_db: YOUR_WEB_LOG_DB #set web_log database
  log_tb: YOUR_WEB_LOG_TB #set web_log table
  primary_cookie: td_ssc_id #td_ssc_id or td_client_id
  sub_cookie: td_client_id
  td_ssc_id: td_ssc_id #td_ssc_id未取得の場合 "'na'"
  user_id: user_id #set user_id column未取得の場合 "'na'"
  custom_param: ",hoge,hogehoge,hogehogehoge" #追加カラムがない場合未記載
  check_click: true
  click_db: YOUR_CLICK_LOG_DB
  click_tb: YOUR_CLICK_LOG_TB
  click_col: click_url
  primary_cookie_click: td_ssc_id #td_ssc_id or td_client_id
  sub_cookie_click: td_client_id
  td_ssc_id_click: td_ssc_id #td_ssc_id未取得の場合 "'na'"
  user_id_click: "'na'" #set user_id column未取得の場合 "'na'"
  custom_param_click: ",click_text" #追加カラムがない場合未記載
  read_click: true
  read_db: YOUR_READ_LOG_DB
  read_tb: YOUR_READ_LOG_TB
  read_col: scroll_depth_threshold
  primary_cookie_read: td_ssc_id #td_ssc_id or td_client_id
  sub_cookie_read: td_client_id
  td_ssc_id_read: td_ssc_id #td_ssc_id未取得の場合 "'na'"
  user_id_read: "'na'" #set user_id column未取得の場合 "'na'"
  custom_param_read: ",text" #追加カラムがない場合未記載
