---
origin_dict: true
dict:
- dict_db: dict_db
  dict_tb: dict_tb
  name_col: name_col
  tags_col: tags_col
  kana_col: kana_col
  wordclass_col: "'カスタム名刺'"
  fulltext_db: fulltext_db
  fulltext_tb: fulltext_tb
  fl_host: td_host
  fl_path: td_path
  fl_title: td_title
  fl_description: td_description
  orinal_tag_score: 0.02

s3_dict:
  endpoint: s3-us-east-2.amazonaws.com #YOUR_S3_ENDPOINT
  bucket: YOUR_BUCKET
  path: YOUR_PATH
  directory: dictionary
  connection: YOUR_S3_TD_CONNECTOR

score_weights:
  pf: 2.0
  ac: 2.0
  spot: 2.0
  orinal_tag: 0.2

proc_main_coefficient: 0.3

master_segment: 111111 #set master_segment number
cdp_behavior_table: cdp_behavior_table

input_workflow_category_list: true
input_category:
- keywords: ビール
  flag: ビール
  score_weight: 0.5
- keywords: カフェ|コーヒ|抹茶|パフェ|チョコレート|ケーキ|cafe|チーズ|パンケーキ|プリン|生地|食パン
  flag: カフェ
  score_weight: 0.5

install_category_list: true
install_category_list_db: install_category_list_db
install_category_list_tb: install_category_list_tb
individual_score_on: NULL #個別設定したい場合
individual_score_off: -- #install_allで一括設定したい場合
install_category:
- flag: sweets
  cg: スイーツ・菓子類全般
  score_weight: 0.5
- flag: convenience_store_sweets
  cg: コンビニスイーツ
  score_weight: 0.5  
- flag: gift
  cg: 手土産・お取り寄せ
  score_weight: 0.99

