---
log_db: sample_db
log_tb: sample_tb
key_id: td_client_id
check_host: sample.jp
seg_score_accidental_low: 1
seg_score_low_middle: 1.5
seg_score_middle_loyal: 2.3
user_id_check: false
multi_media_check: false #true or false / read_depth cnt exists true
multi_media_col_mane: media
multi_media_content: split_part(td_path, '/', 2) #どこでパースするかはメディアごとに異なります。またメディアIDカラムがある場合メディアIDカラムをセット
calc_period: -1
