---
base_db: multi_report
list_db: list_database
list_tb: list
interval: 7
network:
- name: a
  platform_id: 1111
  tb: log_network_a
  device_col: device
  key_id_col: id_a
  view_col: view
  imp_col: impression
  view_sec_col: seconds
- name: b
  platform_id: 2222
  tb: log_network_b
  device_col: device
  key_id_col: id_b
  view_col: view
  imp_col: impression
  view_sec_col: seconds
- name: c
  platform_id: 3333
  tb: log_network_c
  device_col: device
  key_id_col: id_c
  view_col: view
  imp_col: impression
  view_sec_col: seconds