---
master_segment: xxxxxxx
check_host_flag: --
check_host: na
user_mst_check: false #true or false / click cnt exists true
wed_log_db: WEB_LOG_DB
wed_log_tb: WEB_LOG_TABLE
web_log_user_id: user_id
user_mst_db: USER_MST_DB
user_mst_tb: USER_MST_TABLE
user_id: id
email: email
birthday: birthday
gender: sex
regist_day: regist_day
prefecture: prefecture
address_1: address_1
address_2: address_2
address_3: address_3
first_name: first_name
last_name: last_name
phone: phone
zip_code: zip_code
